| Part Number |      Core     | I/Os (High Current) | Operating Temperature (°C) min | Operating Temperature (°C) max |       Other timer functions        | Supply Voltage (V) min | Supply Voltage (V) max | Internal RAM Size (kB) | FLASH Size (kB) (Prog) | Operating Frequency (MHz) (Processor speed) | Supply Current (µA) (Lowest power mode) typ | Supply Current (µA) (Run mode (per Mhz)) typ |         Display controller        | Comparator | Integrated op-amps | I2C typ | SPI typ | USART  typ |          USB Type          | I2S typ | CAN  typ | Additional Serial Interfaces | D/A Converters  (12 bit) typ | Timers (16 bit) typ | Timers (32 bit) typ | Parallel Interfaces | UART typ | A/D Converters (12-bit channels) | A/D Converters (16-bit channels) | TRNG typ | Crypto-HASH |
|-------------|---------------|---------------------|--------------------------------|--------------------------------|------------------------------------|------------------------|------------------------|------------------------|------------------------|---------------------------------------------|---------------------------------------------|----------------------------------------------|-----------------------------------|------------|--------------------|---------|---------|------------|----------------------------|---------|----------|------------------------------|------------------------------|---------------------|---------------------|---------------------|----------|----------------------------------|----------------------------------|----------|-------------|
| STM32F429ZI | ARM Cortex-M4 |                 114 |                            -40 |                             85 | 2 x WDG, RTC,  24-bit down counter |                    1.7 |                    3.6 |                    256 |                   2048 |                                         180 |                                         1.7 |                                          208 | LCD TFT Controller up to 1024x728 | -          | -                  |       3 |       6 |          4 | USB OTG FS + USB OTG FS/HS |       2 |        2 | Ethernet,SAI                 |                            2 |                  12 |                   2 | FMC,SDIO            |        4 |                               24 | -                                | -        | -           |
