Navigation
#Vorwort
    (Anerkennungsgespräch)
    ~~V-Modell~~
Einleitung
Vorarbeit
    Ursprüngliche Motivation
    Fertigungsproblematik
    Industriell gefertigte Aktoren
Projektziel und Anforderungskatalog
Terminologie
    Galvanometer
    System
    Modell
        Beispiel
    Modellbildung
Formelzeichen und Einheiten
    Zeitabhängige Größen
    Konstanten
Projektplan und V-Modell
Modellbildungsprozess
    Generisches Modell
        Mathematische Zusammenhänge
            Translation und Rotation
            Energiebilanz in allgemeiner Form
            Impulsbilanzgleichung
    Aktoren
        Klassifizierung
        Herstellerspezifikation
        Elektrische Komponenten
            Elektrisches Teilsystem
            Back-EMF
            Elektrisch generiertes Drehmoment
            Positionssensor
        Mechanische Komponenten
            Lastmoment
            Mechanisches Teilsystem
            Verbindung der Teilsysteme
        Aktor Gesamtmodell
        Testsignale
            Problematik der Sättigung
    Stellglied / Leistungsteil
    Signalkonditionierung
Softwarearchitektur
    Was ist Softwarearchitektur?
    Model-Driven Architecture (MDA)
        Unified Modeling Language (UML)
        UML2 - Industriestandard
        Diagramme als Sicht
    Architekturkomponenten
Plattform
    Warum ARM?
    Warum Cortex-M4?
        Architektur-Profil M oder R
    CMSIS - Der Cortex-Software Schnittstellen-Standard
    Multiply-Accumulate / Sum-Of-Products
    Texas Instruments C2000 und der CLA
    Software
Software und Simulation
    Hardwarenahe Programmierung (C)
        Entwicklungsumgebungen und Toolchains
        SW4STM32 Toolchain/IDE
        Dokumentation
    PC-Schnittstellenprogramm (C++ / Qt)
        Live-Zustandsüberwachung
        Parameter Manipulation
    Schaltungssimulation und Netzwerkanalyse (LTspice)
    System- und Reglersimulation (Simulink)
    Schnittstelle Spice-to-Simulink (MATLAB)
        LTspice <-> MATLAB: Freqency response estimation
    Debuggen in sw4stm32
Quelldaten generieren
Verifizierung / Systemtests
    Step-by-Step
    Regelalgorithmen testen:
        RC-Glied direkt an gepufferten DAC
        Testsignale im uC erzeugen
        Oszibilder mit MATLAB-Simulation vergl.
Regelungstechnik
    Diskretisierungsverfahren
    Regelungsnormalform
Gesamtsystem
Quellenangaben
Notes
Trash

