# Navigation #
| Tastenkombination |                              Funktion                             |
|-------------------|:-----------------------------------------------------------------:|
| __Alt+Links__     | Rücksprung zur Ausgangsposition nach Aktivierung eines Hyperlinks <br><span style="background-color: yellow"> Testen ob auch in Windows 7/10: IExplorer, firefox, Chrome </span> |

</center>
