# Software und Simulation #
In diesem Abschnitt soll zum einen auf die Umsetzung des Software-Teils eingegangen werden, zum anderen wird die Simulationsumgebung vorgestellt. Der Bereich _Software und Simulation_ wird wie folgt untergliedert: 

<yellowBg 

## Hardwarenahe Programmierung (__C__) ##
## PC-Schnittstellenprogramm (__C++ / Qt__) ##
### Echtzeit-Zustandsüberwachung ###
### Parameter Manipulation ###
## Schaltungssimulation / Netzwerkanalyse (__LTspice__) ##
## System- und Reglersimulation (__Simulink__) ##
## Schnittstelle Spice-to-Simulink (__MATLAB__)
### LTspice <-> MATLAB: Freqency response estimation  ###
- Antialiasing- und Rekonstruktionsfiltern
- dem unterlegten, analogen Stromregler
- Endstufe sowie Stellglied
- Signalkonditionierung

## Debuggen in sw4stm32 ##
## DOXYGEN!!! ##
## CMSIS ##
