# Simulationen und Verifizierung #
## Step-by-Step ##
<!-- ## Spice: Geht die Simulation nicht ... ## -->
<!-- ###  ... geht auch der Testaufbau nicht! ### -->
## Regelalgorithmen testen: ##
### RC-Glied direkt an gepufferten DAC ###
### Testsignale im uC erzeugen ###
### Oszibilder mit MATLAB-Simulation vergl. ###
