# Important Notes #
- MathJax:
    + Math Settings:
        * Zoom Trigger: No Zoom
        * Zoom Factor: 200%
        * Math Renderer: 
            - Common HTML
            - Fast Preview
        * Scale all Math: 90%
    + Accessibillity

