# Trash #
<a name="refTableElectric"> </a>
<center>

| Elektrische Spezifikationen    |                              |                |                      |
| ---                            | ---                          | ---            | ...                  |
| Coil Resistance                | 1.5 Ohm                      |                | $\pm\SI\{10\}\{\%\}$ |
| Coil Inductance                | 160µH                        |                | $\pm\SI\{10\}\{\%\}$ |
| Back EMF Voltage               | 0.17mV/degree/sec            | 9.74mV/rad/sec | $\pm\SI\{10\}\{\%\}$ |
| RMS Current                    | 4.6A @ T_case=50°C, Max      |                |                      |
| Peak Current                   | 25A, Max                     |                |                      |
| Small Angle Step Response Time | 0.5ms (inertia matched load) |                |                      |

</center>

<a name="refTableMechanic"> </a>
<center>

| Mechanical Specifications        |                    |             |                      |
| ---                              | ---                | ---         | ...                  |
| Rated Angular Excursion          | 40°                |             |                      |
| Rotor Inertia                    | 0.6 gm.cm^2        | 6e-8 kg.m^2 | $\pm\SI\{10\}\{\%\}$ |
| Torque Constant                  | 9.3 10^4 dyne.cm/A | 9.3e-3 Nm/A | $\pm\SI\{10\}\{\%\}$ |
| Maximum Coil Temperature         | 110°C              |             |                      |
| Thermal Resistance (Coil - Case) | 1.5°C/Watt, Max    |             |                      |

</center>
<span style="font-size: 80%">$\;\;\;1\;dyne.cm \;\;\;\Leftrightarrow\;\;\; 1\times 10^{-7} Nm$
$\;\;\;1\;gm.cm^2 \;\;\;\Leftrightarrow\;\;\; 1\times 10^{-7} kg.m^2$</span>
<center>

| Position Detector                |                                         |                      |
| ---                              | ---                                     |                      |
| Linearity                        | 99.9%, Minimum, over 40 degrees         |                      |
| Scale Drift                      | 50PPM/°C, Maximum                       |                      |
| Zero Drift                       | 15 microradians/°C, Maximum             |                      |
| Repeatability, Short Term        | 8 microradians                          |                      |
| Output Signal, Common Mode       | 585µA @ AGC voltage=10VDC               | $\pm\SI\{20\}\{\%\}$ |
| Output Signal, Differential Mode | 14.5µA/° @ common mode current of 585µA | $\pm\SI\{20\}\{\%\}$ |

</center>
<p style="margin: 0em 18em 0em 9em; background: -webkit-linear-gradient(top left, #ccc 20%, #ccc 40%, rgba(250, 250, 250, 0) 100%);"> 
</p>

kann nach Newton's 3. Axiom [_"Actio et Reactio"_](https://de.wikipedia.org/wiki/Actio_und_Reactio) $\Rightarrow \vec{F_{A\rightarrow B}} = -\vec{F_{B\rightarrow A}} $ folgende Bestimmungsgleichung aufgestellt werden: 

$$ \omega(t)=L \cdot \frac{\partial~\varphi}{\partial~t} $$


$$ \vec{L} = \vec{r} \times \vec{p} = \vec{r} \times \left( m\cdot\vec{v}\right) \label{eqRmv} $$

Durch die zeitliche Ableitung $\dot{\vec{L}}$ erhält man den Drehmomentvektor $\vec{M}$. Da sowohl Ortsvektor $\vec{r}(t)$ wie auch der Geschwindigkeitsvektor $\vec{v}(t)$ des Impulses $\vec{p}(t)$ Funktionen in _t_  darstellen, muss Gleichung \eqref{eqRmv} über die Produktregel differenziert werden:  

\begin{align}
\frac{\partial}{\partial\,t} \vec{L} &= \dot{\vec{r}} \times \left( m \cdot \vec{v} \right) \nonumber \\\ 
\dot{\vec{L}} &= \dot{\vec{r}} \times \left( m \cdot \vec{v} \right) + \vec{r} \times \left( m \cdot \dot{\vec{v}} \right) \nonumber
\end{align}

> Bei der Translation charakterisiert der Impuls den Bewegungszustand eines Körpers. In analoger Weise lässt sich bei der Rotation der Bewegungszustand eines rotierenden starren Körpers durch die physikalische Größe Drehimpuls kennzeichnen.[^fnAngularMomentum] 

---
__Parameterableitung eines Vektors mit konstanter Länge__ 
Ist der Betrag eines Vektors $\vec{r}(x)$ als konstant zu betrachten, so steht dieser stehts senkrecht zu seiner Ableitung:    

\begin{align}
\vec{r} = const \;\;\;&\Rightarrow\;\;\; \left| \vec{r} \right| = const \;\;\;\Rightarrow\;\;\; \sqrt{\vec{r} \cdot \vec{r}} = const \nonumber \\\ &\Rightarrow\;\;\; \vec{r} \cdot \vec{r} = const \label{eqrr}
\end{align}

Unter Anwendung der Produktregel wird die erste Ableitung von \eqref{eqrr} nach $x$ gebildet:

$$ \frac{\partial\,\vec{r}}{\partial\,x} \cdot \vec{r} \;+\; \vec{r} \cdot \frac{\partial\,\vec{r}}{\partial\,x} = 2 \cdot \left( \vec{r} \cdot \frac{\partial}{\partial\,x}\vec{r} \right) = 0 $$

Hieraus folgt, dass der Vektor senkrecht zu seiner Ableitung stehen muss.
$$ \vec{L} = J \cdot \vec{\omega} $$



<img src="./pics/energiebilanzDeriv.svg" title="Energiebilanz eines beliebigen Energiespeichers" align="rigth" height="138x" style="float:right; margin: 0em 0em 0em .5em;"/>
Die im Rahmen dieser Arbeit relevanten,  Erhaltungssätze 
Für den Fall 
Der Drehimpulsvektor $\vec{L}$ eines starren Körpers wird definirt als Kreuzprodukt aus Ortsvektor und Impulsvektor. 

Auch in der technischen Mechanik stützen sich viele mathematische Ansätze der Dynamik auf Bilanzgleichungen diverser physikalischer Größen. Zum Beispiel gilt für jedes energetisch abgeschlossene System (Bsp.: idealer Feder-Masse-Schwingkreis, idealer LC-Schwingkreis) stehts, dass die Momentanenergie zu jedem Zeitpunkt $t \ge 0$ identisch mit der Energie zum Zeitpunkt $t=0$ übereinstimmt. In diesem Fall bestimmt die _Anfangsbedingung_ das Energieniveau des Systems. 
<p style="margin-top: 2em; background-color: yellow; padding: 1em"> Die Gesetze zur __*Erhaltung*__ der _Masse_, der _Energie_ und des _Impulses_ sind fundamental. Aus diesen Erhaltungssätzen lassen sich domänenübergreifende, aber auch vollkommen unspezifische Bilanzgleichungen formulieren, d.h. unabhängig von der "Bauform" der Prozesse. </p><p style="text-align: right; margin-top: -1em; margin-bottom: 2.5em"> vergl. [[Iser:2008, 61]][@Iser:2008]</p>

M_{FR} \;\propto\; \omega &\;\;\;\Leftrightarrow\;\;\; M_{FR} = K_{FR} \cdot\boldsymbol{\dot\varphi} \label{eqLinearFriction} \\\
M_{EL} \;\propto\; i_L &\;\;\;\Leftrightarrow\;\;\; M_{EL} = K_{EL}\cdot i_L \label{eqLinearElTorque}
$$ \mathsf{G(s)=  \frac{\small{Y}(s)}{\small{U}(s)} = \frac{z_3\cdot s^2+z_2\cdot s+z_1}{s^3+n_3\cdot s^2+n_2\cdot s+n_1} }$$ 

$\pm 20°\,s^{-1}$
$\pm 20\si{°/s}$
$\pm 20°\si{\per s}$
$\pm 20\si[per-mode=symbol]{°/s}$
$\pm 20\Si{°/s}$
$\Si{\ang{\pm 20} \per s}$
$\pm 20 \Si{\degree \per s}$
$\ang{100}$
$100°$


60 64 63 93 82 92 42 54