# Vorwort #
Diese Ausarbeitung ist in Anlehnung an das Anerkennungsgespräch vom 02.11.2016 entstanden und dient der Einschätzung des Wissensstands.

Gesprächsnotiz:

| Modul    | Bezeichnung                                 |
| -------- | ------------------------------------------  |
| ELT201   | Softwareentwurf                             |
| ELT203   | Betriebssysteme                             |
| ELT204   | Hardwarenahe Programmierung I               |
| ELT237   | Hardwarenahe Programmierung II (ab SS17)    |
| ELT236   | Embedded Systems                            |
| ELT247   | ~~Werkzeuge der Informations- und Kommun.~~ |

1. Doku __*C*__-Projekt
    - Umsetzung, nicht gesamten Weg
    - nicht Architektur 
2. Doku __*C++*__-Projekt bzw. OO
    - Allg. wie bei 1.
    - "Wozu Unterklasse XY erstellt" etc.
3. Doku __*Embedded*__-Projekt 
    - plattformübergreifende Inhalte
    - inkl. Modell etc.

## V-Modell ##
An einigen Stellen dieser Dokumentation wird auf Inhalte des V-Modells verwiesen bzw. auf diese Referenziert. Allgemein ist unter der Bezeichnung _V-Modell_ das aktuelle _V-Modell *XT*_[^fnV-Modell-XT] zu verstehen. 

