# Formelzeichen und Einheiten #
Aufgrund der hohen Anzahl an Abkürzung, vor allem aber der nicht immer intuitiv ableitbaren mechanischen und mechatronischen Kenngrößen, wurde an dieser Stelle ein eigenes Kapitel als zentrales Nachschlagewerk verfasst.   

## Zeitabhängige Größen ##

| Bezeichnung           | Symbol               | Einheit            | <span style="color: #bbb">engl. Bezeichnung</span>               |
| --------------------- | :------------------: | :----------------: | ---------------------------------------------------------------- |
| Spulenstrom           | $i_L$                | $\si A$            | <span style="color: #bbb"> Coil current              </span>     |
| Elektr. Drehmoment    | $M_\{EL\}$           | $\si\{N.m\}$       | <span style="color: #bbb"> Electrical torque         </span>     |
| Reibungsmoment        | $M_\{FR\}$           | $\si\{N.m\}$       | <span style="color: #bbb"> Rotor dynamic friction torque </span> |
| Torsionsfedermoment   | $M_\{TB\}$           | $\si\{N.m\}$       | <span style="color: #bbb"> Torsion bar torque        </span>     |
| Drehimpuls            | $L_\omega$           | $\si\{N.m.s\}$     | <span style="color: #bbb"> Angular momentum          </span>     |
| Winkelposition        | $\varphi_\{rad\}$    | $\si\{rad\}$       | <span style="color: #bbb"> Angular position          </span>     |
|                       | $\varphi_\{deg\}$    | $\si\{°\}$         | <span style="color: #bbb">                           </span>     |
| Winkelgeschwindigkeit | $\omega$             | $\Si\{rad\per s\}$ | <span style="color: #bbb"> Angular velocity          </span>     |
| Stromregler Eingang   | $U_\{ccI\}$          | $\si V$            | <span style="color: #bbb"> Current controller input  </span>     |
| Stromregler Ausgang   | $U_\{ccO\}$          | $\si V$            | <span style="color: #bbb"> Current controller output </span>     |
| Spannung Messshunt    | $U_\{sh\}$           | $\si V$            | <span style="color: #bbb"> Shunt voltage             </span>     |

## Konstanten ##
Herstellerangaben 

| Bezeichnung              | Symbol      | Einheit                | <span style="color: #bbb">engl. Bezeichnung</span>          |
| ------------------------ | :---:       | :--------------------: | ----------------------------------------------------------- |
| Wicklungsinduktivität    | $L$         | $\si H$                | <span style="color: #bbb">Coil inductance</span>            |
| Wicklungswiderstand      | $R_L$       | $\si\{\Omega\}$        | <span style="color: #bbb">Coil resistance</span>            |
| Messwiderstand           | $R_\{SH\}$  | $\si\{\Omega\}$        | <span style="color: #bbb">Current shunt resistance</span>   |
| Massenträgheit d. Rotors | $J_R$       | $\si\{kg.m^2\}$        | <span style="color: #bbb">Rotor inertia</span>              |
| EMF-Konstante            | $K_\{EMF\}$ | $\Si\{V.s\per rad\}$   | <span style="color: #bbb">Back EMF const.</span>            |
| Torsionsfederkonstante   | $K_\{TB\}$  | $\Si\{N.m\per rad\}$   | <span style="color: #bbb">Torsion bar torque const.</span>  |
| Reibungskonstante        | $K_\{FR\}$  | $\Si\{N.m.s\per rad\}$ | <span style="color: #bbb">Friction torque const.</span>     |
| El. Drehmomentkonstante  | $K_\{EL\}$  | $\Si\{N.m\per A\}$     | <span style="color: #bbb">El. magnetic torque const.</span> |

