# Software und Simulation #
In diesem Abschnitt soll zum einen auf die Umsetzung des Software-Teils eingegangen werden, zum anderen wird die Simulationsumgebung vorgestellt. Der Bereich _Software und Simulation_ wird wie folgt untergliedert: 

1. hardwarenahe Programmierung in __C__
2. Entwurf eines kleinen, plattformunabhängigen GUI als Schnittstellenprogramm in __C++ / Qt__
    * Echtzeit-Zustandsüberwachung
    * Anpassung von Regelparametern etc.
3. Elektroniksimulation mittels __LTspice__
4. System- und Reglersimulation in __Simulink__
5. Schnittstelle zwischen Hardware-Simulation (__Spice__) und Reglermodell (__Simulink__)
    * MATLAB Skript zur <u>vollautomatischen</u> Modellgenerierung von Schaltungskomponenten wie
        - Antialiasing- und Rekonstruktionsfiltern
        - dem unterlegten, analogen Stromregler
        - Endstufe sowie Stellglied


## Debuggen in sw4stm32 ##
## DOXYGEN!!! ##
## CMSIS ##
