# Geschlossene Simulationsumgebung #
## Umsetzung in MATLAB / Simulink ##
## "frequency response model estimation" ##
## copy ltspice conform laplace function of the estimated system  ##
## Aktoren -> Simulink Modelle  ##
## Endstufe -> LTspice -> MATLAB ##
## Levelshifter -> LTspice -> MATLAB ##
## Antialias / Rekonstruktionsfilter -> MATLAB ##
